apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-delete-tasks-api
  ports:
    - port: {{ .Values.deletetask.serviceport }}
      targetPort: {{ .Values.deletetask.containerPort }}
