apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-get-task-api-ingress
spec:
  ingressClassName: {{ .Values.gettask.ingressClassName }}
  rules:
  - host: {{ .Values.gettask.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-todo-get-task-api
            port: 
              number: {{ .Values.gettask.serviceport }}
