apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-get-task-api-ingress
spec:
  ingressClassName: {{ .Values.gettask.ingressClassName }}
  rules:
  - host: {{ .Release.Name }}-get-tasks-api.6weathers.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-todo-get-task-api
            port: 
              number: {{ .Values.gettask.serviceport }}
