apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-get-task-api
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-get-task-api
  ports:
    - port: {{ .Values.gettask.serviceport }}
      targetPort: {{ .Values.gettask.containerPort }}
